BSCSCAN_API_KEY = "IQSM2XJ8BXRKPPRBKKTWMJZSCCHFVN92S8"
TELEGRAM_BOT_TOKEN = "7922802876:AAGe8YP6cJeqra9V3cTArasfumWPFbClPRM"
# BSC Node Provider (Using Ankr's public RPC)
WEB3_PROVIDER_URL = "https://rpc.ankr.com/bsc"
